import psycopg2
import pandas as pd
import numpy

conn = psycopg2.connect("dbname=polovniautomobili user=postgres password=123")
cur = conn.cursor()

cur.execute("TRUNCATE TABLE boja CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE emisiona_klasa CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE gorivo CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE grad CASCADE")
conn.commit()
cur.execute("TRUNCATE TABLE karoserija CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE klima CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE materijal CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE menjac CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE ostecenje CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE pogon CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE poreklo CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE stanje CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE vlasnistvo CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE zemlja_uvoza CASCADE ")
conn.commit()
cur.execute("TRUNCATE TABLE marka CASCADE")
conn.commit()

conn.commit() # <- We MUST commit to reflect the inserted data
cur.close()
conn.close()
