import psycopg2
import pandas as pd
import numpy

conn = psycopg2.connect("dbname=polovniautomobili user=postgres password=123")
cur = conn.cursor()

cur.execute("TRUNCATE TABLE boja")
conn.commit()
cur.execute("TRUNCATE TABLE boja")
conn.commit()
cur.execute("TRUNCATE TABLE emisiona_klasa")
conn.commit()
cur.execute("TRUNCATE TABLE gorivo")
conn.commit()
cur.execute("TRUNCATE TABLE grad")
conn.commit()
cur.execute("TRUNCATE TABLE karoserija")
conn.commit()
cur.execute("TRUNCATE TABLE klima")
conn.commit()
cur.execute("TRUNCATE TABLE materijal")
conn.commit()
cur.execute("TRUNCATE TABLE menjac")
conn.commit()
cur.execute("TRUNCATE TABLE ostecenje")
conn.commit()
cur.execute("TRUNCATE TABLE pogon")
conn.commit()
cur.execute("TRUNCATE TABLE poreklo")
conn.commit()
cur.execute("TRUNCATE TABLE stanje")
conn.commit()
cur.execute("TRUNCATE TABLE vlasnistvo")
conn.commit()
cur.execute("TRUNCATE TABLE zemlja_uvoza")
conn.commit()
cur.execute("TRUNCATE TABLE marka CASCADE")
conn.commit()
cur.execute("TRUNCATE TABLE automobili")
conn.commit()

conn.commit() # <- We MUST commit to reflect the inserted data
cur.close()
conn.close()
